[package]
name = "melos"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
cpal = "0.16.0"
hound = "3.5.1"
ndarray = "0.16.1"
rustfft = "6.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
